feat: sonarcloud support added
SchweizerischeBundesbahnen/ch.sbb.polarion.extension.generic pull request #125
Opened 2024-08-12 09:52 UTC by grigoriev

### Proposed changes

Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).

### Checklist

Before creating a PR, run through this checklist and mark each as complete:
- [ ] I have read the [`CONTRIBUTING`](CONTRIBUTING.md) document
- [ ] If applicable, I have added tests that prove my fix is effective or that my feature works
- [ ] If applicable, I have checked that any relevant tests pass after adding my changes
- [ ] I have updated any relevant documentation

2024-08-13 09:44 UTC, ariwk requested changes
still no coverage metrics are published

2024-08-24 10:37 UTC, ariwk commented on README.md
> +[![Lines of Code](https://sonarcloud.io/api/project_badges/measure?project=SchweizerischeBundesbahnen_ch.sbb.polarion.extension.generic&metric=ncloc)](https://sonarcloud.io/summary/new_code?id=Schwei
here must be defined which information we want to publish

2024-08-24 14:37 UTC, ariwk approved these changes

2024-08-24 17:20 UTC, grigoriev commented on .github/workflows/maven-build.yml
> +        run: mvn --batch-mode -Dmaven.test.skip=true deploy -P gpg-sign -P nexus-staging
`-Dmaven.test.skip=true`this should not be here: we are publishing test jar as well

2024-08-25 18:52 UTC, Jumas approved these changes

2024-08-25 18:53 UTC, merged